apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/Ameausoone/discover-kustomize/iso/overlays/staging?ref=master

namespace: staging

images:
  - name: busybox
    newName: ameausoone/env
    newTag: latest

configMapGenerator:
  - name: my-config
    literals:
      - app_env=dev
      - app_db_host=dbhost
