name: staging

on:
  push:
    paths:
      - 'staging/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Kubernetes toolset
        uses: stefanprodan/kube-tools@v1.0.0
        with:
          kubectl: 1.16.2
          kustomize: 3.2.3
          command: kustomize build staging
         
