name: staging

on:
  push:
    paths:
      - 'staging/*'

jobs:
  build:
    entrypoint: ""
    runs-on: zillownyc/kustomize:v3.1.0
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: kustomize build staging